export const authUrls = {
    login: 'auth/user/signin',
    register: 'auth/user/signup',
    forgetpassword:'auth/user/forgetpassword',
    changepassword:'auth/user/updatepassword',
    orgSingup:'invite/accept-invitation',
    pendingrequests:'certificate/viewingRequests/all',
    pendingrequesthistoryverifier: 'certificate/verifier/verifier-history',
    accept:'certificate/accept/viewCertReq/',
    reject:'certificate/reject/viewCertReq/',
    requestHistory:'certificate/historyOfViewer/viewCertReq',
    withdrawrequestsforissuer:'certificate/withdraw/viewCertReq',
    user:'user/me',
    upload:'user/profilePicture',
    update:'user/getProfilePicture',
    editInfo:'user/updateUser',
    dashboard:'user/verifier/dashboard',
    issuerdashboard:'user/issuer/dashboard',
    recentdocs:'user/recentDocuments',
    notification:'notification',
    allverifierrequests:'certificate/allVerifierCertRequest/',
    acceptverifierdocs:'certificate/candidate/acceptVerifier/',
    rejectverifierdocs:'certificate/candidate/rejectVerifier/',
    withdrawrequestsforverifier:'certificate/withdraw/verifierCertReq',
    admindashboard:'organization/listOfallMembers'
};